package recipes

import (
	"github.com/marrow16/gogol/logic"
	"github.com/marrow16/gogol/patterns"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func (r *Recipe) SaveAsRle(origGrid *logic.Grid, filename string, originator string) (err error) {
	var grid *logic.Grid
	if grid, err = logic.NewGrid(origGrid.Height, origGrid.Width, origGrid.WrapMode, origGrid.BoundaryMode); err == nil {
		grid.Rule = origGrid.Rule
		if grid, _, err = r.Run(grid); err == nil {
			var pattern patterns.Pattern
			if pattern, err = patterns.NewPatternFromGrid(grid); err == nil {
				pattern.Comments = []string{
					"Generated by GoGoL (https://github.com/marrow16/gogol)",
				}
				if r.Name != nil {
					pattern.Name = "From recipe " + *r.Name
				} else {
					pattern.Name = "From recipe " + filename
				}
				pattern.Origination = originator
				saveFilename := filename[:len(filename)-len(filepath.Ext(filename))] + ".recipe.rle"
				var f *os.File
				if f, err = os.Create(saveFilename); err == nil {
					defer func() {
						_ = f.Close()
					}()
					err = patterns.PatternRleEncode(pattern, f)
				}
			}
		}
	}
	return err
}

func (r *Recipe) Run(origGrid *logic.Grid) (newGrid *logic.Grid, resized bool, err error) {
	newGrid = origGrid
	if r.GridSettings != nil {
		ht, wd, wm, bm, rule := origGrid.Height, origGrid.Width, origGrid.WrapMode, origGrid.BoundaryMode, origGrid.Rule
		if r.GridSettings.Height != nil && *r.GridSettings.Height != ht {
			resized = true
			ht = *r.GridSettings.Height
		}
		if r.GridSettings.Width != nil && *r.GridSettings.Width != wd {
			resized = true
			wd = *r.GridSettings.Width
		}
		if r.GridSettings.WrapMode != nil {
			wm = logic.WrapModeFromString(*r.GridSettings.WrapMode, wm)
		}
		if r.GridSettings.BoundaryMode != nil {
			bm = logic.BoundaryModeFromString(*r.GridSettings.BoundaryMode, bm)
		}
		if r.GridSettings.Rule != nil {
			if nr, err := logic.NewRuleRle("", *r.GridSettings.Rule); err == nil {
				rule = nr
			}
		}
		if resized {
			var ng *logic.Grid
			if ng, err = logic.NewGrid(ht, wd, wm, bm); err == nil {
				newGrid = ng
				newGrid.Rule = rule
			} else {
				return
			}
		} else {
			newGrid.WrapMode, newGrid.BoundaryMode, newGrid.Rule = wm, bm, rule
			newGrid.Clear()
		}
	}
	r.doDos(newGrid, 0, 0, r.Do, &lastDimensions{})
	return
}

type lastDimensions struct {
	width  int
	height int
}

func (r *Recipe) doDos(grid *logic.Grid, cy, cx int, dos []Do, last *lastDimensions) {
	for _, do := range dos {
		if do.At != nil {
			cy, cx = do.At.move(cy, cx)
		}
		if do.Move != nil && !do.Move.isAfter() {
			cy, cx = do.Move.move(cy, cx, last.height, last.width)
		}
		rotate := patterns.Rotate0
		if do.Rotate != nil {
			rotate = patterns.Rotation(*do.Rotate % 4)
		}
		if do.Place != nil {
			if patt, ok := r.Patterns[*do.Place]; ok {
				if do.Move != nil && !do.Move.isAfter() {
					cy, cx = do.Move.move(cy, cx, last.height, last.width)
				}
				ptn := patt.pattern
				last.height, last.width = ptn.Height, ptn.Width
				ptn.Draw(grid, cy, cx, rotate)
				if do.Move != nil && do.Move.isAfter() {
					cy, cx = do.Move.move(cy, cx, last.height, last.width)
				}
				repeats := calcRepeats(do.Repeat, ptn.Height, ptn.Width, grid.Height, grid.Width, cy, cx)
				for i := 0; i < repeats; i++ {
					if do.Move != nil && !do.Move.isAfter() {
						cy, cx = do.Move.move(cy, cx, last.height, last.width)
					}
					ptn.Draw(grid, cy, cx, rotate)
					if do.Move != nil && do.Move.isAfter() {
						cy, cx = do.Move.move(cy, cx, last.height, last.width)
					}
				}
			} else if v, ok := r.Vars[*do.Place]; ok && v != nil {
				if do.Move != nil && !do.Move.isAfter() {
					cy, cx = do.Move.move(cy, cx, last.height, last.width)
				}
				do.VarOps.performOnVar(v, false)
				ptn := v.toPattern(grid.Height, grid.Width, cy, cx)
				ptn.Draw(grid, cy, cx, rotate)
				last.height, last.width = ptn.Height, ptn.Width
				if do.Move != nil && do.Move.isAfter() {
					cy, cx = do.Move.move(cy, cx, last.height, last.width)
				}
				do.VarOps.performOnVar(v, true)
				repeats := calcRepeats(do.Repeat, ptn.Height, ptn.Width, grid.Height, grid.Width, cy, cx)
				for i := 0; i < repeats; i++ {
					if do.Move != nil && !do.Move.isAfter() {
						cy, cx = do.Move.move(cy, cx, last.height, last.width)
					}
					do.VarOps.performOnVar(v, false)
					ptn = v.toPattern(grid.Height, grid.Width, cy, cx)
					ptn.Draw(grid, cy, cx, rotate)
					last.height, last.width = ptn.Height, ptn.Width
					if do.Move != nil && do.Move.isAfter() {
						cy, cx = do.Move.move(cy, cx, ptn.Height, ptn.Width)
					}
					do.VarOps.performOnVar(v, true)
				}
			}
		}
		r.doDos(grid, cy, cx, do.Do, last)
	}
}

func calcRepeats(num *Number, ph, pw int, gh, gw int, cy, cx int) int {
	if num != nil {
		raw := strings.ToLower(num.raw())
		switch raw {
		case "gh", "gridheight", "grid-height":
			ah := gh - cy + 1
			return (ah / ph) + 1
		case "gw", "gridwidth", "grid-width":
			aw := gw - cx + 1
			return (aw / pw) + 1
		default:
			if nn, err := strconv.Atoi(raw); err == nil {
				return nn
			}
		}
	}
	return 0
}
