package help

var contentSizingWrapping = content{
	"Use the ", bold("Sizing/Wrapping/Boundaries"), " popout from the ", MainMenu.link("main menu"), " to adjust various settings on grid sizing and behaviour.\n\n",
	"Use the ", bold("Grid size Width"), " and ", bold("Height"), " inputs to set the desired size for the grid - the grid size is only updated by pressing the ", button("Resize"), " button.\n",
	"Press the ", button("Fit screen"), " button to resize the grid to fill the available screen size (according to current cell size and zoom rate).\n",
	"The ", bold("Keep cells"), " checkbox is used to determine whether the grid alive/dead cells are preserved during resizing.\n\n",
	bold("Wrapping mode"), " determines how cells at the edges of the grid interact with cells on the opposite edges:",
	hanging{indent: 20,
		prefix:  content{bold("• None"), " - "},
		content: content{"grid edges do not wrap."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Horizontal"), " - "},
		content: content{"left and right edges wrap around to each other."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Vertical"), " - "},
		content: content{"top and bottom edges wrap around to each other."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Toroidal"), " - "},
		content: content{"all grid edges connect to their opposite edge."},
	},
	"When grid edges are not wrapped, the ", bold("Boundary mode"), " determines how cells beyond those edges are treated. They may be considered either ", bold("Dead cells"), " or ", bold("Alive cells"), " when calculating the neighbours of cells at the grid edge.\n\n",
	"The ", bold("Cell size"), " input determines the size of each grid cell in pixels (1–32). Updating this value will take immediate effect.\n\n",
	bold("Randomize %"), " input is used to determine the percentage of alive cells when randomizing the grid (from the ", MainMenu.link("main menu"), " or pressing ", keys{altMac, "R"}, ").\n",
	"Note: The randomize % setting only determines probability of alive cell - not overall grid density. ",
	"To specify an overall random density, create a ", ShortCuts.link("shortcut"), " using action ", code("randomize-population"), ".\n",
}
