package help

import "github.com/marrow16/gogol/cmd/gui/icons"

var contentMainMenu = content{
	"The main menu can be shown by clicking the ", iconText{image: icons.Burger},
	" button on the status bar or by pressing key\u00a0", keys{altMac, "M"}, "\n\n",
	"The menu contains the following options:\n\n",
	bold("Help"), " or press key ", keys{"F1"},
	indent{indent: 20, spaceAfter: 8, content: content{"Show this help screen."}},
	bold("About"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows application version and information."}},
	bold("Patterns"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", Patterns.link("Patterns"), " popout."}},
	bold("Captured Patterns"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", CapturedPatterns.link("Captured Patterns"), " popout."}},
	bold("Load Patterns"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", LoadPatterns.link("Load Patterns"), " popout."}},
	bold("Instrumentation"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", Instrumentation.link("Instrumentation"), " popout."}},
	bold("Shortcuts"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", ShortCuts.link("Shortcuts"), " popout."}},
	bold("Meta Rules"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", MetaRules.link("Meta Rules"), " popout."}},
	bold("Collected Rules"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", CollectedRules.link("Collected Rules"), " popout."}},
	bold("Grid Recipes"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", GridRecipes.link("Grid Recipes"), " popout."}},
	bold("Size/Wrapping/Boundaries"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", SizingWrapping.link("Size/Wrapping/Boundaries"), " popout."}},
	bold("Stepping"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", Stepping.link("Stepping"), " popout."}},
	bold("Colors"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", Colors.link("Colors"), " popout."}},
	bold("Snapshot"), " or press key ", keys{altMac, "S"},
	indent{indent: 20, spaceAfter: 8, content: content{"Takes a snapshot of the current grid."}},
	bold("Undo to snapshot"), " or press key ", keys{altMac, "Z"},
	indent{indent: 20, spaceAfter: 8, content: content{"Restores the grid to the last snapshot."}},
	bold("Export Grid"), " or press key ", keys{altMac, "X"},
	indent{indent: 20, spaceAfter: 8, content: content{"Exports the current grid as a ", code(".rle"), " file in the documents/GoGoL folder."}},
	bold("Import Grid"),
	indent{indent: 20, spaceAfter: 8, content: content{"Shows the ", ImportGrid.link("Import Grid"), " popout."}},
	bold("Edit mode"), " or press key ", keys{altMac, "E"},
	indent{indent: 20, spaceAfter: 8, content: content{"   Places the grid into edit mode.  See ", topicLink{Topic: Editor, Italic: true}}},
	bold("Randomize"), " or press key ", keys{altMac, "R"},
	indent{indent: 20, spaceAfter: 8, content: content{"Clears the current grid and adds random alive cells."}},
	bold("Random Noise"), " or press key ", keys{altMac, "N"},
	indent{indent: 20, spaceAfter: 8, content: content{"Adds random alive cells to the current grid."}},
	bold("Clear"), " or press key ", keys{altMac, "C"},
	indent{indent: 20, spaceAfter: 8, content: content{"Clears all cells in the current grid."}},
}
