package help

import "github.com/marrow16/gogol/cmd/gui/icons"

var contentInstrumentation = content{
	"The ", bold("Instrumentation"), " popout is accessed from the ", MainMenu.link("main menu"), ".\n",
	"Instrumentation provides tools for analysing and recording the behaviour of the grid. Each instrument can be independently enabled or disabled using its checkbox.\n\n",
	"The following tools are available:\n\n",
	bold("Repeat Detect"), "\n",
	"When enabled, monitors successive generations looking for a grid state that has occurred previously. When a repeat is found, ", bold("First"), " and ", bold("Repeat"), " show the generations containing the matching states, and ", bold("Period"), " shows the number of generations between them.\n",
	"Also, when a repeat is detected for the first time, the running simulation will stop and the repeat found is notified on the ", StatusBar.link("statusbar"),
	hanging{indent: 10, gap: 10,
		prefix:  content{button("Reset")},
		content: content{"clears the current repeat detection history."},
	},
	hanging{indent: 10, gap: 10,
		prefix:  content{button("Save Report")},
		content: content{"saves a report of the detected repeat as a ", code(".json"), " file in the documents/GoGoL folder."},
	},
	separator{spaceBefore: 8, spaceAfter: 8},
	bold("Record"), "\n",
	"When enabled, retains previous generations, allowing the simulation to be stepped backwards and for animations to be saved.",
	hanging{indent: 10, gap: 10,
		prefix:  content{bold("Steps recorded")},
		content: content{"shows the number of generations currently retained."},
	},
	hanging{indent: 10, gap: 10,
		prefix: content{bold("Skip back by")},
		content: content{"determines how many generations are skipped when using the skip-back control.\n",
			"Press ", keys{altMac, keyBack}, " or use ", iconText{image: icons.SkipBackward}, " button on ", StatusBar.link("statusbar")},
	},
	hanging{indent: 10, gap: 10,
		prefix:  content{button("Reset")},
		content: content{"to discard the current recorded history."},
	},
	hanging{indent: 10, gap: 10,
		prefix:  content{button("Save Animation")},
		content: content{" to save the recorded steps as an animation - ", bold("Gif"), " or ", bold("Mp4"), " file."},
	},
	italic("Note: The Mp4 option is only available when "), code("ffmpeg"), italic(" is installed."), " [see ", url("https://ffmpeg.org/"), "]\n",
	italic("WARNING: Saving animations above 1000 or so steps can produce very large files!"),
	separator{spaceBefore: 8, spaceAfter: 8},
	bold("Heat Mapping"), "\n",
	"Accumulates cell activity over successive generations that can be visualised as a heat map image.\n",
	bold("Type"), " determines the information accumulated:",
	hanging{indent: 20,
		prefix:  content{bold("• Activity"), " - "},
		content: content{"how frequently each cell changes state."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Age"), " - "},
		content: content{"the current age of alive cells."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Births"), " - "},
		content: content{"how frequently a cell becomes alive."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Freshness"), " - "},
		content: content{"how recently each cell changed state."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Longevity"), " - "},
		content: content{"the maximum continuous age ever attained by each cell."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Occupancy"), " - "},
		content: content{"how many generations each cell location has been alive."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• Phase Parity"), " - "},
		content: content{"distinguishes activity occurring on odd and even generations."},
	},
	hanging{indent: 20,
		prefix:  content{bold("• All"), " - "},
		content: content{"collects all the above heat map measurements."},
	},
	hanging{indent: 10, gap: 10,
		prefix:  content{button("Reset")},
		content: content{"to clear the accumulated heat map data."},
	},
	hanging{indent: 10, gap: 10,
		prefix: content{button("Reveal")},
		content: content{"to display the heat map image.\n",
			"Or press ", keys{altMac, "H"}, ". See also ", HeatMap.link("heat map display")},
	},
	hanging{indent: 10, gap: 10,
		prefix: content{button("Save Image")},
		content: content{" to save the heat map image as a ", code(".png"), " file in the documents/GoGoL folder.\n",
			"If ", bold("All"), " is active - images for each heat map type are saved.",
		},
	},
}
