package help

var contentShortcuts = content{
	"Use the ", bold("Shortcuts"), " popout from the ", MainMenu.link("main menu"), " to create or edit keyboard shortcuts.\n\n",
	"A shortcut can be assigned to any ", bold("Key"), " and is activated using ", keys{altMac}, " combined with your chosen key.\n\n",
	"Each key has ", bold("Actions"), " assigned to it - see ", ShortCutsRef.link("reference"), " for available actions.\n\n",
	italic("Note: Shortcuts "), boldItalic("do not"), italic(" prohibit you assigning keys already assigned by GoGoL!"),
}

var contentShortCutsRef = content{
	"This page shows describes all of the shortcut actions that can be used to create ", ShortCuts.link("shortcuts"),
	table{
		borders: true,
		padding: 4,
		columns: []tableColumn{
			{
				width:  30,
				header: "Action",
			},
			{
				header: "Description",
			},
		},
		rows: []tableRow{
			{{codeCopyable("borders:bool")}, {"Sets the current grid cell borders on/off (", code("true"), "|", code("false"), ")"}},
			{{codeCopyable("boundary-mode:mode")}, {"Sets the current grid boundary ", italic("mode"), " (", code(`Dead`), "|", code(`Alive`), ")"}},
			{{codeCopyable("cell-color-alive:color")}, {"Sets the current grid cell alive ", italic("color"), " (as HTML hex color, ", code(`#rrggbb`), ")"}},
			{{codeCopyable("cell-color-dead:color")}, {"Sets the current grid cell dead ", italic("color"), " (as HTML hex color, ", code(`#rrggbb`), ")"}},
			{{codeCopyable("cell-color-border:color")}, {"Sets the current grid cell border ", italic("color"), " (as HTML hex color, ", code(`#rrggbb`), ")"}},
			{{codeCopyable("cell-size:n")}, {"Sets the current grid cell size to ", italic("n"), " (3-100)"}},
			{{codeCopyable("clear")}, {"Clears the current grid"}},
			{{codeCopyable("export")}, {"Exports the current grid as RLE"}},
			{{codeCopyable("export-image")}, {"Exports the current grid as PNG"}},
			{{codeCopyable("grid-height:n")}, {"Sets the current grid height to ", italic("n"), " (2-1000)"}},
			{{codeCopyable("grid-size:wXh")}, {"Sets the current grid size to ", italic("w"), " (width) X ", italic("h"), " (height)"}},
			{{codeCopyable("grid-width")}, {"Sets the current grid width to ", italic("n"), " (2-1000)"}},
			{{codeCopyable("heat-map")}, {"Turns on the heat map instrument (", code(`Activity`), ")"}},
			{{codeCopyable("heat-map:type")}, {"Turns on the heat map instrument with ", italic("type"), " (", code(`Activity`), "|", code(`Occupancy`), "|", code(`Births`), "|", code(`Freshness`), "|", code(`Phase Parity`), "|", code(`All`), ")\n", italic("(other values will turn heat mapper off)")}},
			{{codeCopyable("heat-map-reveal")}, {"Reveals (shows) the current heat map"}},
			{{codeCopyable("heat-map-save")}, {"Saves the current heat map as a .png"}},
			{{codeCopyable("log:format")}, {"Logs a message to ", code(`output.log`), " file - `format` is the same as `name:format`"}},
			{{codeCopyable("max-adjacents:n")}, {"Alters the current grid so that no cell can have more than ", italic("n"), " alive neighbours"}},
			{{codeCopyable("name:format")}, {"Sets the name for output files (e.g. exports, heat map images)\nThe name can be any string that is a valid filename/filepath - plus any of the following format tokens:",
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%rule"), " e.g. transposed to `B2/S23`"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%born"), " e.g. transposed to `B2`"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%survives"), " e.g. transposed to `S23`"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%perm"), " e.g. transposed to `4108`"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%rand"), " transposed to current randomization setting"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%now"), " transposed to a date/time stamp"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%r"), " transposed to repeat iteration(s)"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%R"), " transposed to last (current) repeat iteration"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%step"), " transposed to the current step of the grid"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%population"), " transposed to the current population of the grid"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%repeat-found"), " transposed to whether a repeat was found (`true`|`false`)"}},
				hanging{gap: 10, indent: 10, prefix: "•", content: content{codeCopyable("%repeat-first"), " ", codeCopyable("%repeat-at"), " and ", codeCopyable("%repeat-period"), " transposed to repeat information"}}},
			},
			{{codeCopyable("random-additions")}, {"Applies random additions (alive cells) to the current grid (according to current randomization setting)"}},
			{{codeCopyable("random-additions:n")}, {"Applies random additions (alive cells) to the current grid - according to ", italic("n"), " (0-100)"}},
			{{codeCopyable("random-changes")}, {"Applies random changes (noise) to the current grid (according to current randomization setting)"}},
			{{codeCopyable("random-changes:n")}, {"Applies random changes (noise) to the current grid - according to ", italic("n"), " (0-100)"}},
			{{codeCopyable("random-cull")}, {"Applies random cull to the current grid (according to current randomization setting)"}},
			{{codeCopyable("random-cull:n")}, {"Applies random cull to the current grid - according to ", italic("n"), " (0-100)"}},
			{{codeCopyable("randomization++")}, {"Increments the randomization setting"}},
			{{codeCopyable("randomization--")}, {"Decrements the randomization setting"}},
			{{codeCopyable("randomization:n")}, {"Sets the randomization setting to ", italic("n"), " (0-100)"}},
			{{codeCopyable("randomize")}, {"Randomize the current grid (according to current randomization setting)"}},
			{{codeCopyable("randomize:n")}, {"Randomize the current grid  - according to ", italic("n"), " (0-100)"}},
			{{codeCopyable("randomize-population")}, {"Randomize the population of the current grid (according to current randomization setting)\n", italic("Note: This differs from `randomize` because that randomizes each cell in isolation - therefore it is not at all guaranteed that the final grid will have the specified % density. This action ensures that the overall grid density matches the specified randomization setting.")}},
			{{codeCopyable("randomize-population:n")}, {"Randomize the population of the current grid - according to ", italic("n"), " (0-100)"}},
			{{codeCopyable("record")}, {"Turns the record instrument on"}},
			{{codeCopyable("record:1|0")}, {"Turns the record instrument on or off"}},
			{{codeCopyable("record-animation-save")}, {"Saves the current recording as an animation ", italic("(only works when recording is on - e.g. `record:1`)")}},
			{{codeCopyable("record-animation-format:gif|mp4")}, {"Sets the current recording animation format"}},
			{{codeCopyable("repeat-detect")}, {"Turns the repeat detect instrument on"}},
			{{codeCopyable("repeat-detect:1|0")}, {"Turns the repeat detect instrument on or off"}},
			{{codeCopyable("repeat-detect-save")}, {"Saves the current repeat detection (if enabled) as a report json"}},
			{{codeCopyable("repeat:n,...,...")}, {"Repeats the following actions (comma separated) ", italic("n"), " times\nExample:",
				codeBlock{code: "repeat:100,randomize,step-ahead-by:500,heat-map-save"}, "Repeats can also be 'nested', example:",
				codeBlock{code: "repeat:5,rule-perm++,randomize,heat-map:Activity,repeat:10,step-ahead-by:10,heat-map-save`"}}},
			{{codeCopyable("replay-snapshot")}, {"Replays a snapshot\nResets the grid to the last snapshot (without removing the snapshot from the stack)\n", italic("Note: If there is no current snapshot - the grid is randomized and a snapshot added")}},
			{{codeCopyable("rule-born-with:x")}, {"Sets or adjusts the current life rule born with - where ", italic("x"), " can be:",
				hanging{indent: 10, gap: 10, prefix: "•", content: "`23` sets to `B23`"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`|23` ORs with 2 and 3 (effectively turning just those on)"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`&23` ANDs with 2 and 3"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`!23` flips 2 and 3"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`!` flips all - e.g. `B23` becomes `B0145678`"},
				italic("Note: the current survives with, `S`, is unchanged")}},
			{{codeCopyable("rule-born-with++")}, {"Increments the current life rule born with permutation (high order 9 bits)"}},
			{{codeCopyable("rule-born-with--")}, {"Decrements the current life rule born with permutation (high order 9 bits)"}},
			{{codeCopyable("rule-perm++")}, {"Increments the current life rule permutation"}},
			{{codeCopyable("rule-perm--")}, {"Decrements the current life rule permutation"}},
			{{codeCopyable("rule-perm:n")}, {"Sets the current life rule permutation to ", italic("n"), " (0-262143)"}},
			{{codeCopyable("rule-int++")}, {"Increments the current life rule integer"}},
			{{codeCopyable("rule-int--")}, {"Decrements the current life rule integer"}},
			{{codeCopyable("rule-int:n")}, {"Sets the current life rule integer to ", italic("n"), " (0-262143)"}},
			{{codeCopyable("rule-survives-with:x")}, {"Sets or adjusts the current life rule survives with - where ", italic("x"), " can be:",
				hanging{indent: 10, gap: 10, prefix: "•", content: "`23` sets to `S23`"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`|23` ORs with 2 and 3 (effectively turning just those on)"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`&23` ANDs with 2 and 3"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`!23` flips 2 and 3"},
				hanging{indent: 10, gap: 10, prefix: "•", content: "`!` flips all - e.g. `S23` becomes `S0145678`"},
				italic("Note: the current born with, `B`, is unchanged")}},
			{{codeCopyable("rule-survives-with++")}, {"Increments the current life rule survives with permutation (low order 9 bits)"}},
			{{codeCopyable("rule-survives-with--")}, {"Decrements the current life rule survives with permutation (low order 9 bits)"}},
			{{codeCopyable("rule:name|rle")}, {"Sets the current life rule (by ", italic("name"), " or specified ", italic("rle"), ", e.g. `B2/S23`)"}},
			{{codeCopyable("run-recipe")}, {"Runs the currently selected grid recipe"}},
			{{codeCopyable("run-recipe:filename")}, {"Runs the grid recipe for the specified ", italic("filename")}},
			{{codeCopyable("run")}, {"Runs simulation on the current grid"}},
			{{codeCopyable("sleep:ms")}, {"Sleeps for a given ", italic("ms"), " (millisecond) period"}},
			{{codeCopyable("snapshot")}, {"Snapshots the current grid"}},
			{{codeCopyable("step-ahead++")}, {"Increments the current step ahead setting"}},
			{{codeCopyable("step-ahead--")}, {"Decrements the current step ahead setting"}},
			{{codeCopyable("step-ahead")}, {"Performs a step ahead (by current step ahead setting)"}},
			{{codeCopyable("step-ahead:n")}, {"Sets the current step ahead setting to ", italic("n"), " (1-9999)"}},
			{{codeCopyable("step-ahead-by:n")}, {"Performs a step ahead by ", italic("n"), " (>0)"}},
			{{codeCopyable("step-back-by:n")}, {"Performs a step back by ", italic("n"), " (>0) ", italic("(only works when recording is on - e.g. `record:1`)")}},
			{{codeCopyable("step-delay++")}, {"Increments the current step delay setting"}},
			{{codeCopyable("step-delay--")}, {"Decrements the current step delay setting"}},
			{{codeCopyable("step-delay:ms")}, {"Sets the current step delay to ", italic("ms"), " (0-2000)"}},
			{{codeCopyable("step")}, {"Performs a single simulation step on the current grid"}},
			{{codeCopyable("stop")}, {"Stops simulation on the current grid"}},
			{{codeCopyable("undo-to-snapshot")}, {"Restores grid to last snapshot"}},
			{{codeCopyable("wrap-mode:mode")}, {"Sets the current grid wrap ", italic("mode"), " (", code(`none`), "|", code(`horizontal`), "|", code(`vertical`), "|", code(`all`), "|", code(`toroidal`), ")"}},
			{{codeCopyable("next-meta-rule:meta")}, {"Skips to the next rule in `meta` and sets the current rule to that (see ", MetaRules.link("meta rules"), ")"}},
			{{codeCopyable("previous-meta-rule:meta")}, {"Skips to the previous rule in `meta` and sets the current rule to that (see ", MetaRules.link("meta rules"), ")"}},
			{{codeCopyable("iterate-meta-rule:meta")}, {"Iterates over a meta rule (similar to `repeat:n`)\n", italic("Note: If the meta rule contains commas, it should enclosed in single or double quotes.")}},
			{{codeCopyable("add-collected-rule")}, {"Adds the current grid rule to the collected rules (see ", CollectedRules.link("collected rules"), ")"}},
			{{codeCopyable("remove-collected-rule")}, {"Removes the current grid rule from the collected rules"}},
			{{codeCopyable("next-collected-rule")}, {"Skips to the next rule in collected rules"}},
			{{codeCopyable("previous-collected-rule")}, {"Skips to the previous rule in collected rules"}},
			{{codeCopyable("iterate-collected-rules")}, {"Iterates over collected rules"}},
		},
		spaceBefore: 8,
	},
}
