package help

var contents = map[Topic]content{
	About:                contentAbout,
	CapturedPatterns:     contentCapturedPatterns,
	CollectedRules:       contentCollectedRules,
	Colors:               contentColors,
	Editor:               contentEditor,
	FileFinder:           contentFileFinder,
	GridRecipes:          contentGridRecipes,
	GridRecipesReference: contentGridRecipesReference,
	HeatMap:              contentHeatMap,
	ImportGrid:           contentImportGrid,
	Index:                contentIndex,
	Instrumentation:      contentInstrumentation,
	Keys:                 contentKeys,
	LoadPatterns:         contentLoadPatterns,
	MainMenu:             contentMainMenu,
	MetaRules:            contentMetaRules,
	MetaRulesRef:         contentMetaRulesRef,
	Patterns:             contentPatterns,
	PlacePattern:         contentPlacePattern,
	Rules:                contentRules,
	ShortCuts:            contentShortcuts,
	ShortCutsRef:         contentShortCutsRef,
	SizingWrapping:       contentSizingWrapping,
	StatusBar:            contentStatusBar,
	Stepping:             contentStepping,
}
