package help

import "github.com/marrow16/gogol/cmd/gui/icons"

var contentStatusBar = content{
	"The status bar is split into three sections:\n",
	hanging{
		prefix: []any{bold("Step/Mode"), " - "},
		content: []any{"shows the current step or the current mode.\n",
			"When simulating, the ", bold("%"), " is the percent of cells that changed",
			" and ", bold("Hz"), " is generations per second."},
	},
	"\n",
	hanging{
		prefix:  []any{bold("Rule"), " - "},
		content: []any{"shows the current rule (click or press ", keys{altMac, "L"}, " to change ", Rules.link("Rule"), ")"},
	},
	"\n", bold("Control buttons:"),
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.Play}, " - "},
		content: content{"start the simulation ", keys{altMac, keyEnter}},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.Pause}, " - "},
		content: content{"pause the simulation ", keys{altMac, keyEnter}},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.Step}, " - "},
		content: content{"step the simulation ", keys{altMac, keyRight}},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.SkipForward}, " - "},
		content: content{"step ahead the simulation ", keys{altMac, keyTab}, " (see ", Stepping, ")"},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.ZoomIn}, " - "},
		content: content{"zoom in."},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.ZoomOut}, " - "},
		content: content{"zoom out."},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.Burger}, " - "},
		content: content{"show the main menu ", keys{altMac, "M"}, " (see ", MainMenu, ")"},
	},
	hanging{indent: 10,
		prefix: content{"Additionally (if ", Instrumentation.link("Record instrument"), " is enabled):"},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.Backward}, " - "},
		content: content{"step back ", keys{altMac, keyLeft}},
	},
	hanging{indent: 20,
		prefix:  content{iconText{image: icons.SkipBackward}, " - "},
		content: content{"skip backward the simulation ", keys{altMac, keyBack}},
	},
}
