package main

import "github.com/marrow16/gogol/patterns"

var alphabet = map[string]patterns.Pattern{
	"!": {Height: 9, Width: 1, Cells: []bool{
		true,
		true,
		true,
		true,
		true,
		false,
		true,
		false,
		false,
	}},
	"\"": {Height: 9, Width: 3, Cells: []bool{
		true, false, true,
		true, false, true,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
	}},
	"#": {Height: 9, Width: 5, Cells: []bool{
		false, true, false, true, false,
		false, true, false, true, false,
		true, true, true, true, true,
		false, true, false, true, false,
		true, true, true, true, true,
		false, true, false, true, false,
		false, true, false, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"$": {Height: 9, Width: 5, Cells: []bool{
		false, false, true, false, false,
		false, true, true, true, false,
		true, false, true, false, true,
		false, true, true, false, false,
		false, false, true, true, false,
		true, false, true, false, true,
		false, true, true, true, false,
		false, false, true, false, false,
		false, false, false, false, false,
	}},
	"£": {Height: 9, Width: 5, Cells: []bool{
		false, false, true, true, false,
		false, true, false, false, true,
		false, true, false, false, false,
		true, true, true, true, false,
		false, true, false, false, false,
		false, true, false, false, false,
		true, true, true, true, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"%": {Height: 9, Width: 6, Cells: []bool{
		false, false, false, false, false, false,
		true, true, false, false, false, true,
		true, true, false, false, true, false,
		false, false, false, true, false, false,
		false, false, true, false, false, false,
		false, true, false, false, true, true,
		true, false, false, false, true, true,
		false, false, false, false, false, false,
		false, false, false, false, false, false,
	}},
	"&": {Height: 9, Width: 5, Cells: []bool{
		false, true, false, false, false,
		true, false, true, false, false,
		false, true, false, false, false,
		true, false, true, false, true,
		true, false, false, true, false,
		true, false, false, true, false,
		false, true, true, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"'": {Height: 9, Width: 1, Cells: []bool{
		true,
		true,
		false,
		false,
		false,
		false,
		false,
		false,
		false,
	}},
	"(": {Height: 9, Width: 2, Cells: []bool{
		false, true,
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		false, true,
		false, false,
	}},
	")": {Height: 9, Width: 2, Cells: []bool{
		true, false,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		true, false,
		false, false,
	}},
	"*": {Height: 9, Width: 5, Cells: []bool{
		false, false, false, false, false,
		true, false, true, false, true,
		false, true, true, true, false,
		false, false, true, false, false,
		false, true, true, true, false,
		true, false, true, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"+": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		false, false, false,
		false, true, false,
		true, true, true,
		false, true, false,
		false, false, false,
		false, false, false,
		false, false, false,
	}},
	",": {Height: 9, Width: 1, Cells: []bool{
		false,
		false,
		false,
		false,
		false,
		false,
		true,
		true,
		false,
	}},
	"-": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		true, true, true,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
	}},
	".": {Height: 9, Width: 1, Cells: []bool{
		false,
		false,
		false,
		false,
		false,
		false,
		true,
		false,
		false,
	}},
	"/": {Height: 9, Width: 3, Cells: []bool{
		false, false, true,
		false, false, true,
		false, true, false,
		false, true, false,
		false, true, false,
		true, false, false,
		true, false, false,
		false, false, false,
		false, false, false,
	}},
	"0": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"1": {Height: 9, Width: 2, Cells: []bool{
		false, true,
		true, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, false,
		false, false,
	}},
	"2": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		false, false, false, true,
		false, false, true, false,
		false, true, false, false,
		true, false, false, false,
		true, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"3": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		false, false, false, true,
		false, false, true, false,
		false, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"4": {Height: 9, Width: 4, Cells: []bool{
		false, false, true, false,
		false, true, true, false,
		false, true, true, false,
		true, false, true, false,
		true, true, true, true,
		false, false, true, false,
		false, false, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"5": {Height: 9, Width: 4, Cells: []bool{
		true, true, true, true,
		true, false, false, false,
		true, true, true, false,
		true, false, false, true,
		false, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"6": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		true, false, false, false,
		true, true, true, false,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"7": {Height: 9, Width: 4, Cells: []bool{
		true, true, true, true,
		false, false, false, true,
		false, false, true, false,
		false, false, true, false,
		false, true, false, false,
		false, true, false, false,
		false, true, false, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"8": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"9": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	":": {Height: 9, Width: 1, Cells: []bool{
		false,
		false,
		false,
		true,
		false,
		false,
		true,
		false,
		false,
	}},
	";": {Height: 9, Width: 1, Cells: []bool{
		false,
		false,
		false,
		true,
		false,
		false,
		true,
		true,
		false,
	}},
	"<": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, true,
		false, false, true, false,
		false, true, false, false,
		true, false, false, false,
		false, true, false, false,
		false, false, true, false,
		false, false, false, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"=": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		false, false, false,
		true, true, true,
		false, false, false,
		true, true, true,
		false, false, false,
		false, false, false,
		false, false, false,
	}},
	">": {Height: 9, Width: 4, Cells: []bool{
		true, false, false, false,
		false, true, false, false,
		false, false, true, false,
		false, false, false, true,
		false, false, true, false,
		false, true, false, false,
		true, false, false, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"?": {Height: 9, Width: 4, Cells: []bool{
		false, true, true, false,
		true, false, false, true,
		false, false, false, true,
		false, false, true, false,
		false, true, false, false,
		false, false, false, false,
		false, true, false, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"@": {Height: 9, Width: 8, Cells: []bool{
		false, false, true, true, true, true, false, false,
		false, true, false, false, false, false, true, false,
		true, false, false, true, true, false, false, true,
		true, false, true, false, true, false, false, true,
		true, false, true, false, true, false, false, true,
		true, false, false, true, false, true, true, false,
		false, true, false, false, false, false, false, false,
		false, false, true, true, true, true, false, false,
		false, false, false, false, false, false, false, false,
	}},
	"A": {Height: 9, Width: 6, Cells: []bool{
		false, false, true, true, false, false,
		false, false, true, true, false, false,
		false, true, false, false, true, false,
		false, true, false, false, true, false,
		false, true, true, true, true, false,
		true, false, false, false, false, true,
		true, false, false, false, false, true,
		false, false, false, false, false, false,
		false, false, false, false, false, false,
	}},
	"B": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"C": {Height: 9, Width: 5, Cells: []bool{
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, false,
		true, false, false, false, false,
		true, false, false, false, false,
		true, false, false, false, true,
		false, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"D": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"E": {Height: 9, Width: 4, Cells: []bool{
		true, true, true, true,
		true, false, false, false,
		true, false, false, false,
		true, true, true, false,
		true, false, false, false,
		true, false, false, false,
		true, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"F": {Height: 9, Width: 4, Cells: []bool{
		true, true, true, true,
		true, false, false, false,
		true, false, false, false,
		true, true, true, false,
		true, false, false, false,
		true, false, false, false,
		true, false, false, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"G": {Height: 9, Width: 5, Cells: []bool{
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, false,
		true, false, true, true, true,
		true, false, false, false, true,
		true, false, false, true, true,
		false, true, true, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"H": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"I": {Height: 9, Width: 3, Cells: []bool{
		true, true, true,
		false, true, false,
		false, true, false,
		false, true, false,
		false, true, false,
		false, true, false,
		true, true, true,
		false, false, false,
		false, false, false,
	}},
	"J": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, true,
		false, false, false, true,
		false, false, false, true,
		false, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"K": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, true, false,
		true, false, true, false, false,
		true, true, false, false, false,
		true, false, true, false, false,
		true, false, false, true, false,
		true, false, false, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"L": {Height: 9, Width: 4, Cells: []bool{
		true, false, false, false,
		true, false, false, false,
		true, false, false, false,
		true, false, false, false,
		true, false, false, false,
		true, false, false, false,
		true, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"M": {Height: 9, Width: 7, Cells: []bool{
		true, true, false, false, false, true, true,
		true, true, false, false, false, true, true,
		true, false, true, false, true, false, true,
		true, false, true, false, true, false, true,
		true, false, false, true, false, false, true,
		true, false, false, true, false, false, true,
		true, false, false, false, false, false, true,
		false, false, false, false, false, false, false,
		false, false, false, false, false, false, false,
	}},
	"N": {Height: 9, Width: 5, Cells: []bool{
		true, true, false, false, true,
		true, true, false, false, true,
		true, false, true, false, true,
		true, false, true, false, true,
		true, false, false, true, true,
		true, false, false, true, true,
		true, false, false, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"O": {Height: 9, Width: 5, Cells: []bool{
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"P": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, false,
		true, false, false, false, false,
		true, false, false, false, false,
		true, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"Q": {Height: 9, Width: 5, Cells: []bool{
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, true, false, true,
		true, false, false, true, true,
		false, true, true, true, false,
		false, false, false, false, true,
		false, false, false, false, false,
	}},
	"R": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"S": {Height: 9, Width: 5, Cells: []bool{
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, false,
		false, true, true, true, false,
		false, false, false, false, true,
		true, false, false, false, true,
		false, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"T": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, true,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"U": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"V": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, false, true, false,
		false, true, false, true, false,
		false, true, false, true, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"W": {Height: 9, Width: 7, Cells: []bool{
		true, false, false, false, false, false, true,
		true, false, false, false, false, false, true,
		false, true, false, false, false, true, false,
		false, true, false, true, false, true, false,
		false, true, false, true, false, true, false,
		false, false, true, false, true, false, false,
		false, false, true, false, true, false, false,
		false, false, false, false, false, false, false,
		false, false, false, false, false, false, false,
	}},
	"X": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, false, true, false,
		false, false, true, false, false,
		false, true, false, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"Y": {Height: 9, Width: 5, Cells: []bool{
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, false, true, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, true, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"Z": {Height: 9, Width: 5, Cells: []bool{
		true, true, true, true, true,
		false, false, false, false, true,
		false, false, false, true, false,
		false, false, true, false, false,
		false, true, false, false, false,
		true, false, false, false, false,
		true, true, true, true, true,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"[": {Height: 9, Width: 2, Cells: []bool{
		true, true,
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		true, true,
		false, false,
	}},
	"\\": {Height: 9, Width: 3, Cells: []bool{
		true, false, false,
		true, false, false,
		false, true, false,
		false, true, false,
		false, true, false,
		false, false, true,
		false, false, true,
		false, false, false,
		false, false, false,
	}},
	"]": {Height: 9, Width: 2, Cells: []bool{
		true, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		true, true,
		false, false,
	}},
	"^": {Height: 9, Width: 3, Cells: []bool{
		false, true, false,
		true, false, true,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
		false, false, false,
	}},
	"_": {Height: 9, Width: 5, Cells: []bool{
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		false, false, false, false, false,
		true, true, true, true, true,
	}},
	"`": {Height: 9, Width: 2, Cells: []bool{
		true, false,
		false, true,
		false, false,
		false, false,
		false, false,
		false, false,
		false, false,
		false, false,
		false, false,
	}},
	"a": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, false,
		false, false, false, true,
		false, true, true, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"b": {Height: 9, Width: 4, Cells: []bool{
		true, false, false, false,
		true, false, false, false,
		true, true, true, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"c": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, false,
		true, false, false, true,
		true, false, false, false,
		true, false, false, true,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"d": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, true,
		false, false, false, true,
		false, true, true, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"e": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, false,
		true, false, false, true,
		true, true, true, true,
		true, false, false, false,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"f": {Height: 9, Width: 2, Cells: []bool{
		false, true,
		true, false,
		true, false,
		true, true,
		true, false,
		true, false,
		true, false,
		false, false,
		false, false,
	}},
	"g": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, true,
		true, true, true, false,
	}},
	"h": {Height: 9, Width: 4, Cells: []bool{
		true, false, false, false,
		true, false, false, false,
		true, false, true, false,
		true, true, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"i": {Height: 9, Width: 1, Cells: []bool{
		true,
		false,
		true,
		true,
		true,
		true,
		true,
		false,
		false,
	}},
	"j": {Height: 9, Width: 2, Cells: []bool{
		false, true,
		false, false,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		false, true,
		true, false,
	}},
	"k": {Height: 9, Width: 4, Cells: []bool{
		true, false, false, false,
		true, false, false, false,
		true, false, false, true,
		true, false, true, false,
		true, true, false, false,
		true, false, true, false,
		true, false, false, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"l": {Height: 9, Width: 2, Cells: []bool{
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		true, false,
		false, true,
		false, false,
		false, false,
	}},
	"m": {Height: 9, Width: 7, Cells: []bool{
		false, false, false, false, false, false, false,
		false, false, false, false, false, false, false,
		true, true, true, true, true, true, false,
		true, false, false, true, false, false, true,
		true, false, false, true, false, false, true,
		true, false, false, true, false, false, true,
		true, false, false, true, false, false, true,
		false, false, false, false, false, false, false,
		false, false, false, false, false, false, false,
	}},
	"n": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		true, true, true, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"o": {Height: 9, Width: 5, Cells: []bool{
		false, false, false, false, false,
		false, false, false, false, false,
		false, true, true, true, false,
		true, false, false, false, true,
		true, false, false, false, true,
		true, false, false, false, true,
		false, true, true, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"p": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		true, true, true, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, true, true, false,
		true, false, false, false,
		true, false, false, false,
	}},
	"q": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, true,
		false, false, false, true,
	}},
	"r": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		true, true, false,
		true, false, true,
		true, false, false,
		true, false, false,
		true, false, false,
		false, false, false,
		false, false, false,
	}},
	"s": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		false, true, true, true,
		true, false, false, false,
		false, true, true, false,
		false, false, false, true,
		true, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"t": {Height: 9, Width: 2, Cells: []bool{
		false, false,
		true, false,
		true, true,
		true, false,
		true, false,
		true, false,
		false, true,
		false, false,
		false, false,
	}},
	"u": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, false,
		false, false, false, false,
	}},
	"v": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, false,
		false, true, true, false,
		false, false, false, false,
		false, false, false, false,
	}},
	"w": {Height: 9, Width: 5, Cells: []bool{
		false, false, false, false, false,
		false, false, false, false, false,
		true, false, false, false, true,
		true, false, true, false, true,
		true, false, true, false, true,
		false, true, false, true, false,
		false, true, false, true, false,
		false, false, false, false, false,
		false, false, false, false, false,
	}},
	"x": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		true, false, true,
		true, false, true,
		false, true, false,
		true, false, true,
		true, false, true,
		false, false, false,
		false, false, false,
	}},
	"y": {Height: 9, Width: 4, Cells: []bool{
		false, false, false, false,
		false, false, false, false,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		true, false, false, true,
		false, true, true, true,
		false, false, false, true,
		true, true, true, false,
	}},
	"z": {Height: 9, Width: 3, Cells: []bool{
		false, false, false,
		false, false, false,
		true, true, true,
		false, false, true,
		false, true, false,
		true, false, false,
		true, true, true,
		false, false, false,
		false, false, false,
	}},
	"{": {Height: 9, Width: 3, Cells: []bool{
		false, false, true,
		false, true, false,
		false, true, false,
		false, true, false,
		true, false, false,
		false, true, false,
		false, true, false,
		false, true, false,
		false, false, true,
	}},
	"|": {Height: 9, Width: 1, Cells: []bool{
		true,
		true,
		true,
		true,
		true,
		true,
		true,
		false,
		false,
	}},
	"}": {Height: 9, Width: 3, Cells: []bool{
		true, false, false,
		false, true, false,
		false, true, false,
		false, true, false,
		false, false, true,
		false, true, false,
		false, true, false,
		false, true, false,
		true, false, false,
	}},
	"~": {Height: 9, Width: 4, Cells: []bool{
		false, true, false, true,
		true, false, true, false,
		false, false, false, false,
		false, false, false, false,
		false, false, false, false,
		false, false, false, false,
		false, false, false, false,
		false, false, false, false,
		false, false, false, false,
	}},
}
